[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force redirect from /lander to root
[[redirects]]
  from = "/lander"
  to = "/"
  status = 301
  force = true

# Handle all routes properly for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure root domain works without any redirects
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200 
