[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The following redirects are commented out to prevent unwanted behavior
# [[redirects]]
#   from = "/lander"
#   to = "/"
#   status = 301
#   force = true

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[redirects]]
#   from = "/"
#   to = "/index.html"
#   status = 200 
