[build]
  command = "npm run build"
  publish = ".next"

# The Netlify Next.js plugin (Essential Next.js) will automatically handle
# API routes, server-side rendering, image optimization, etc.
# This configuration file ensures the basic build command and publish directory are set.

# If you need to set specific environment variables for the build,
# it's recommended to do so in the Netlify UI under Site settings > Build & deploy > Environment.

# Example for specifying a Node.js version if needed (Netlify usually picks a recent LTS)
# [build.environment]
#   NODE_VERSION = "18"

# You can add redirect and rewrite rules here if necessary.
# For example:
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
